# Generated by Django 4.1.4 on 2022-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testType',
            fields=[
                ('testType_id', models.IntegerField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
