# Generated by Django 4.1.4 on 2022-12-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
