# Generated by Django 4.1.4 on 2022-12-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('testType', '0001_initial'),
        ('doctor', '0001_initial'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('pres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
                ('testType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testType.testtype')),
            ],
        ),
    ]
